workflow test

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -21,4 +21,11 @@ jobs:
         run: npm install
 
       - name: Build Docs
-        run: npm run docs:build
+        run: |
+          npm run docs:build
+          if [ $? -eq 0 ]; then
+            echo "Build succeeded!"
+          else
+            echo "Build failed! -ㅡ-"
+            exit 1
+          fi
